version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: diplom-postgres
    environment:
      POSTGRES_DB: diplom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d diplom"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: diplom-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: diplom-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: diplom-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/diplom?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      API_URL: http://localhost:3001
      APP_URL: http://localhost:3000
      PUBLIC_BASE_URL: http://localhost:3000
    ports:
      - "3001:3001"
    command: sh -c "npm run prisma:deploy && npm run seed && npm run start:prod"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: diplom-web
    depends_on:
      - api
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_APP_NAME: Платформа проектов ТюмГУ
    ports:
      - "3000:3000"

  n8n:
    image: n8nio/n8n:latest
    container_name: diplom-n8n
    depends_on:
      - ollama
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n

  ollama:
    image: ollama/ollama:latest
    container_name: diplom-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  pg_data:
  redis_data:
  n8n_data:
  ollama_data:
